# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-13 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='identifier',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
